---
title: "Gov 50 Final Project"
author: Emily Arbuiso
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to air pollution. I am interested in seeing how air pollution levels vary across different counties in the United States. Finally, I am interested in what factors might determine this variation. The specific factors I will explore are population density, economic activity, poverty, education levels, and blue collar job prevalence.

## Proposal

How do different factors like population density, economic activity, poverty, education level, and blue collar job prevalence affect a county's air pollution? Which of these factors impact air pollution the most? I plan to examine how these different factors could impact the levels of certain air pollutants like NO2, 03, and PM2.5. I hypothesize that there will be negative correlations between air pollution and the factor of education level. Typically, with a higher educational background, one has more knowledge of the climate/environmental science and is more aware of the factors that impact air pollution. Additionally, those with higher educational backgrounds tend to vote for more pro-environmental people that will institute policies that will decrease air pollution. I hypothesize that there will be positive correlations between air pollution and the factors of population density, economic activity, poverty, and blue collar job prevalence. The explanatory variables of interest are population density, economic activity, poverty, education level, and blue collar job prevalence. Population density will be measured by people per square mile. Economic activity will be measured by GDP. Poverty will be measured by average income in U.S. dollars. Educational background will be measured by years of education, both secondary and post-secondary. The outcome variable of interest is air pollution. This will be measured by ppb (parts per billion) or ppm (parts per million) for different pollutants. The years for the data will likely be in the most recent 3 or 4 years. If I observe lower air pollution in counties with higher educational backgrounds, this would support my hypothesis. If I observe higher air pollution in countries with higher educational backgrounds, this would go against my hypothesis. If I observe higher air pollution in counties with higher population densities, more economic activity, more poverty, and higher blue collar jobs, this would support my hypothesis. If I observe lower air pollution in counties with lower values of these factors, this would go against my hypothesis. I will also explore which factors correlate the most with air pollution and which do not. 


